// Package docs Code generated by swaggo/swag at 2025-08-08 15:10:55.372937 +0800 CST m=+1.414282293. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/db/chat/pin": {
            "get": {
                "description": "根据pinId查询TalkGroupChatPinCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据pinId获取聊天消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PinID",
                        "name": "pinId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/chat/pin/all": {
            "get": {
                "description": "获取TalkGroupChatPinCollection的所有数据，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "获取所有聊天消息列表（分页）",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/chat/queue": {
            "get": {
                "description": "根据timestamp查询TalkGroupChatQueueCollection数据，或不传timestamp获取所有数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据timestamp获取聊天队列列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "时间戳",
                        "name": "timestamp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/chat/timestamp": {
            "get": {
                "description": "根据groupId查询TalkGroupChatTimestampCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据groupId获取聊天时间戳列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/collections": {
            "get": {
                "description": "获取所有可用的数据库集合名称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "获取所有可用的数据库集合",
                "responses": {
                    "200": {
                        "description": "集合列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/community/info": {
            "get": {
                "description": "根据communityId查询TalkCommunityInfoCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据communityId获取社区信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "社区ID",
                        "name": "communityId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/community/join": {
            "get": {
                "description": "根据communityId或pinId查询TalkCommunityJoinCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据communityId或pinId获取社区加入记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "社区ID",
                        "name": "communityId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PinID",
                        "name": "pinId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/community/person": {
            "get": {
                "description": "根据communityId或metaId查询TalkCommunityPersonCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据communityId或metaId获取社区成员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "社区ID",
                        "name": "communityId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "MetaID",
                        "name": "metaId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/community/version": {
            "get": {
                "description": "根据communityId或pinId查询TalkCommunityVersionInfoCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据communityId或pinId获取社区版本信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "社区ID",
                        "name": "communityId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PinID",
                        "name": "pinId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/group/info": {
            "get": {
                "description": "根据groupId查询TalkGroupInfoCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据groupId获取群组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/group/join": {
            "get": {
                "description": "根据groupId或pinId查询TalkGroupJoinCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据groupId或pinId获取群组加入记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PinID",
                        "name": "pinId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/group/person": {
            "get": {
                "description": "根据groupId或metaId查询TalkGroupPersonCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据groupId或metaId获取群组成员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "MetaID",
                        "name": "metaId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/group/version": {
            "get": {
                "description": "根据groupId或pinId查询TalkGroupVersionInfoCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据groupId或pinId获取群组版本信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PinID",
                        "name": "pinId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/group/version/all": {
            "get": {
                "description": "获取TalkGroupVersionInfoCollection的所有数据，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "获取所有群组版本信息列表（分页）",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码，从1开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/stats": {
            "get": {
                "description": "获取所有数据库集合的统计信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "获取数据库统计信息",
                "responses": {
                    "200": {
                        "description": "统计信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/db/user/context": {
            "get": {
                "description": "根据metaId查询TalkMetaIdContextListCollection数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库查询"
                ],
                "summary": "根据metaId获取用户群列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MetaID",
                        "name": "metaId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/group-chat/group-chat-list": {
            "get": {
                "description": "获取群组的聊天记录，支持时间戳分页",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "获取群组聊天记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户MetaId",
                        "name": "metaId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "游标，默认为1",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小，默认为20",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "时间戳，用于分页",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回群组聊天记录",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respond.Message"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/respond.GroupChatResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group-chat/group-info": {
            "get": {
                "description": "获取指定群组的详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "获取群组信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回群组信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respond.Message"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/respond.GroupItem"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group-chat/group-list": {
            "get": {
                "description": "获取群组列表，支持分页",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "获取群组列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户MetaId",
                        "name": "metaId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "游标，默认为1",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小，默认为20",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "时间戳",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回群组列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respond.Message"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/respond.GroupResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group-chat/group-member-list": {
            "get": {
                "description": "获取群组的成员列表，支持分页",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "获取群组成员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "游标，默认为1",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小，默认为20",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "时间戳",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回群组成员列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respond.Message"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/respond.GroupMemberResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group-chat/user/latest-group-list": {
            "get": {
                "description": "获取用户的最新聊天群组列表，基于最新聊天时间排序",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "获取最新聊天群组列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户MetaId",
                        "name": "metaId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "游标，默认为1",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小，默认为20",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "时间戳",
                        "name": "timestamp",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回最新聊天群组列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/respond.Message"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/respond.GroupResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ChatType": {
            "type": "integer",
            "format": "int64",
            "enum": [
                0,
                6,
                1,
                2,
                22,
                3,
                4,
                5
            ],
            "x-enum-comments": {
                "ChatTypeEmoji": "群聊 - 表情类型",
                "ChatTypeFile": "群聊 - 文件类型",
                "ChatTypeJoin": "群聊 - 加入类型",
                "ChatTypeLeave": "群聊 - 离开类型",
                "ChatTypeMsg": "群聊 - 信息类型",
                "ChatTypeOpenRed": "群聊 - 抢红包类型",
                "ChatTypeRecycleRed": "群聊 - 回收红包类型",
                "ChatTypeRed": "群聊 - 红包类型"
            },
            "x-enum-descriptions": [
                "群聊 - 信息类型",
                "群聊 - 表情类型",
                "群聊 - 红包类型",
                "群聊 - 抢红包类型",
                "群聊 - 回收红包类型",
                "群聊 - 文件类型",
                "群聊 - 加入类型",
                "群聊 - 离开类型"
            ],
            "x-enum-varnames": [
                "ChatTypeMsg",
                "ChatTypeEmoji",
                "ChatTypeRed",
                "ChatTypeOpenRed",
                "ChatTypeRecycleRed",
                "ChatTypeFile",
                "ChatTypeJoin",
                "ChatTypeLeave"
            ]
        },
        "respond.GroupChatItem": {
            "type": "object",
            "properties": {
                "chatType": {
                    "description": "0-msg, 1-red, 2-img",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ChatType"
                        }
                    ]
                },
                "content": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                },
                "data": {},
                "encryption": {
                    "type": "string"
                },
                "groupId": {
                    "description": "房间ID 唯一",
                    "type": "string"
                },
                "metaId": {
                    "type": "string"
                },
                "metanetId": {
                    "type": "string"
                },
                "nickName": {
                    "description": "UserInfo    *model.UserInfoResp ` + "`" + `json:\"userInfo\"` + "`" + `\nAvatarTxId  string              ` + "`" + `json:\"avatarTxId\"` + "`" + `\nAvatarImage string              ` + "`" + `json:\"avatarImage\"` + "`" + `\nAvatarType  model.AvatarType    ` + "`" + `json:\"avatarType\"` + "`" + `",
                    "type": "string"
                },
                "params": {
                    "description": "通用字段，便于后续新增参数",
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "redMetaId": {
                    "type": "string"
                },
                "replyInfo": {
                    "$ref": "#/definitions/respond.ReplyInfo"
                },
                "replyTx": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "聊天记录时间戳",
                    "type": "integer"
                },
                "txId": {
                    "type": "string"
                }
            }
        },
        "respond.GroupChatResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/respond.GroupChatItem"
                    }
                },
                "nextTimestamp": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "respond.GroupItem": {
            "type": "object",
            "properties": {
                "chatSettingType": {
                    "description": "用于设置发言限制， 0-所有人，1-管理员",
                    "type": "integer"
                },
                "communityId": {
                    "description": "社区Id 唯一",
                    "type": "string"
                },
                "createUserMetaId": {
                    "description": "创建人的metaId",
                    "type": "string"
                },
                "deleteStatus": {
                    "description": "删除状态，0-正常，1-删除",
                    "type": "integer"
                },
                "groupId": {
                    "description": "房间ID 唯一",
                    "type": "string"
                },
                "roomAvatarUrl": {
                    "description": "房间头像url",
                    "type": "string"
                },
                "roomCodeHash": {
                    "description": "roomJoinType为2时有值，codeHash",
                    "type": "string"
                },
                "roomGenesis": {
                    "description": "roomJoinType为2时有值，genesis",
                    "type": "string"
                },
                "roomGenesisSeriesName": {
                    "type": "string"
                },
                "roomJoinType": {
                    "description": "加入方式，1为密码，2为nft",
                    "type": "string"
                },
                "roomLimitAmount": {
                    "description": "roomJoinType为2时有值，token的限制",
                    "type": "integer"
                },
                "roomName": {
                    "description": "创建房间的名称",
                    "type": "string"
                },
                "roomNewestContent": {
                    "description": "房间最新聊天内容",
                    "type": "string"
                },
                "roomNewestMetaId": {
                    "description": "房间最新聊天内容的MetaId",
                    "type": "string"
                },
                "roomNewestProtocol": {
                    "description": "房间最新聊天内容的协议类型",
                    "type": "string"
                },
                "roomNewestTimestamp": {
                    "description": "房间最新聊天的时间戳",
                    "type": "integer"
                },
                "roomNewestTxId": {
                    "description": "房间最新聊天内容的txId",
                    "type": "string"
                },
                "roomNewestUserName": {
                    "description": "房间最新聊天内容的MetaId",
                    "type": "string"
                },
                "roomNinePersonHash": {
                    "description": "房间前9位人员的metaId总hash值",
                    "type": "string"
                },
                "roomNote": {
                    "description": "创建房间的公告",
                    "type": "string"
                },
                "roomStatus": {
                    "description": "\"1\" 未加密时为“1” 加密时为加密后的信息, 保留字段",
                    "type": "string"
                },
                "roomType": {
                    "description": "创建房间的类型 ”1“不加密 “2”加密 加密采用AES加密算法",
                    "type": "string"
                },
                "timestamp": {
                    "description": "创建你房间的时间戳",
                    "type": "integer"
                },
                "txId": {
                    "description": "房间的TxId",
                    "type": "string"
                },
                "userCount": {
                    "description": "房间人数",
                    "type": "integer"
                }
            }
        },
        "respond.GroupMemberItem": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "metaId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "timeStr": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "respond.GroupMemberResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/respond.GroupMemberItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "respond.GroupResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/respond.GroupItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "respond.Message": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "processingTime": {
                    "type": "integer"
                },
                "processingTimeInMid": {
                    "type": "integer"
                }
            }
        },
        "respond.ReplyInfo": {
            "type": "object",
            "properties": {
                "chatType": {
                    "description": "0-msg, 1-red, 2-img",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ChatType"
                        }
                    ]
                },
                "content": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                },
                "encryption": {
                    "type": "string"
                },
                "metaId": {
                    "type": "string"
                },
                "nickName": {
                    "description": "UserInfo    *models.UserInfoResp ` + "`" + `json:\"userInfo\"` + "`" + `",
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "聊天记录时间戳",
                    "type": "integer"
                },
                "txId": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "数据库查询相关API，用于查看Pebble数据库中的数据",
            "name": "数据库查询"
        },
        {
            "description": "群组管理相关API，包括群组信息、成员管理等",
            "name": "群组管理"
        },
        {
            "description": "社区管理相关API，包括社区信息、成员管理等",
            "name": "社区管理"
        },
        {
            "description": "聊天功能相关API，包括消息、队列等",
            "name": "聊天功能"
        },
        {
            "description": "用户管理相关API，包括用户信息、群列表等",
            "name": "用户管理"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "0.0.0.0:7568",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Group Chat API",
	Description:      "群聊服务 API 文档，包含数据库查询、群组管理、社区管理等功能",
	InfoInstanceName: "group-chat-swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
