// Package docs Code generated by swaggo/swag at 2025-08-12 10:12:47.742125 +0800 CST m=+1.161826542. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplategroup_chat_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "tags": [
        {
            "description": "数据库查询相关API，用于查看Pebble数据库中的数据",
            "name": "数据库查询"
        },
        {
            "description": "群组管理相关API，包括群组信息、成员管理等",
            "name": "群组管理"
        },
        {
            "description": "社区管理相关API，包括社区信息、成员管理等",
            "name": "社区管理"
        },
        {
            "description": "聊天功能相关API，包括消息、队列等",
            "name": "聊天功能"
        },
        {
            "description": "用户管理相关API，包括用户信息、群列表等",
            "name": "用户管理"
        }
    ]
}`

// SwaggerInfogroup_chat_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfogroup_chat_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "0.0.0.0:7568",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Group Chat API",
	Description:      "群聊服务 API 文档，包含数据库查询、群组管理、社区管理等功能",
	InfoInstanceName: "group_chat_swagger",
	SwaggerTemplate:  docTemplategroup_chat_swagger,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfogroup_chat_swagger.InstanceName(), SwaggerInfogroup_chat_swagger)
}
