// Package docs Code generated by swaggo/swag at 2025-08-12 10:42:30.836705 +0800 CST m=+1.590711626. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplategroup_chat_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "tags": [
        {
            "description": "Database query related APIs for viewing data in Pebble database",
            "name": "Database Query"
        },
        {
            "description": "Group management related APIs, including group information, member management, etc.",
            "name": "Group Management"
        },
        {
            "description": "Community management related APIs, including community information, member management, etc.",
            "name": "Community Management"
        },
        {
            "description": "Chat function related APIs, including messages, queues, etc.",
            "name": "Chat Function"
        },
        {
            "description": "User management related APIs, including user information, group lists, etc.",
            "name": "User Management"
        }
    ]
}`

// SwaggerInfogroup_chat_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfogroup_chat_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "0.0.0.0:7568",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Group Chat API",
	Description:      "Group Chat Service API documentation, including database queries, group management, community management and other functions",
	InfoInstanceName: "group_chat_swagger",
	SwaggerTemplate:  docTemplategroup_chat_swagger,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

var swaggerRegistered bool

// RegisterSwagger manually register Swagger
func RegisterSwagger() {
	if swaggerRegistered {
		return
	}

	// Use recover to catch duplicate registration panic
	defer func() {
		if r := recover(); r != nil {
			// If registration fails, ignore error
			swaggerRegistered = true
		}
	}()

	swag.Register(SwaggerInfogroup_chat_swagger.InstanceName(), SwaggerInfogroup_chat_swagger)
	swaggerRegistered = true
}
