// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: proto/metacontract.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetaContractService_TransferFt_FullMethodName = "/metacontract.MetaContractService/TransferFt"
	MetaContractService_GetHealth_FullMethodName  = "/metacontract.MetaContractService/GetHealth"
)

// MetaContractServiceClient is the client API for MetaContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaContractServiceClient interface {
	TransferFt(ctx context.Context, in *TransferFtRequest, opts ...grpc.CallOption) (*TransferFtResponse, error)
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type metaContractServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaContractServiceClient(cc grpc.ClientConnInterface) MetaContractServiceClient {
	return &metaContractServiceClient{cc}
}

func (c *metaContractServiceClient) TransferFt(ctx context.Context, in *TransferFtRequest, opts ...grpc.CallOption) (*TransferFtResponse, error) {
	out := new(TransferFtResponse)
	err := c.cc.Invoke(ctx, MetaContractService_TransferFt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaContractServiceClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MetaContractService_GetHealth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaContractServiceServer is the server API for MetaContractService service.
// All implementations must embed UnimplementedMetaContractServiceServer
// for forward compatibility
type MetaContractServiceServer interface {
	TransferFt(context.Context, *TransferFtRequest) (*TransferFtResponse, error)
	GetHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMetaContractServiceServer()
}

// UnimplementedMetaContractServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetaContractServiceServer struct {
}

func (UnimplementedMetaContractServiceServer) TransferFt(context.Context, *TransferFtRequest) (*TransferFtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferFt not implemented")
}
func (UnimplementedMetaContractServiceServer) GetHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedMetaContractServiceServer) mustEmbedUnimplementedMetaContractServiceServer() {}

// UnsafeMetaContractServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaContractServiceServer will
// result in compilation errors.
type UnsafeMetaContractServiceServer interface {
	mustEmbedUnimplementedMetaContractServiceServer()
}

func RegisterMetaContractServiceServer(s grpc.ServiceRegistrar, srv MetaContractServiceServer) {
	s.RegisterService(&MetaContractService_ServiceDesc, srv)
}

func _MetaContractService_TransferFt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferFtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaContractServiceServer).TransferFt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaContractService_TransferFt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaContractServiceServer).TransferFt(ctx, req.(*TransferFtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaContractService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaContractServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaContractService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaContractServiceServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaContractService_ServiceDesc is the grpc.ServiceDesc for MetaContractService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaContractService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metacontract.MetaContractService",
	HandlerType: (*MetaContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferFt",
			Handler:    _MetaContractService_TransferFt_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _MetaContractService_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metacontract.proto",
}
