// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.3
// source: proto/metacontract.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferFtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wif             string         `protobuf:"bytes,1,opt,name=wif,proto3" json:"wif,omitempty"`
	TokenWif        *string        `protobuf:"bytes,2,opt,name=tokenWif,proto3,oneof" json:"tokenWif,omitempty"`
	Token           *TokenTransfer `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	FtChangeAddress *string        `protobuf:"bytes,4,opt,name=ftChangeAddress,proto3,oneof" json:"ftChangeAddress,omitempty"`
	OpreturnData    []string       `protobuf:"bytes,5,rep,name=opreturnData,proto3" json:"opreturnData,omitempty"`
	ChangeAddress   *string        `protobuf:"bytes,6,opt,name=changeAddress,proto3,oneof" json:"changeAddress,omitempty"`
}

func (x *TransferFtRequest) Reset() {
	*x = TransferFtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFtRequest) ProtoMessage() {}

func (x *TransferFtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFtRequest.ProtoReflect.Descriptor instead.
func (*TransferFtRequest) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{0}
}

func (x *TransferFtRequest) GetWif() string {
	if x != nil {
		return x.Wif
	}
	return ""
}

func (x *TransferFtRequest) GetTokenWif() string {
	if x != nil && x.TokenWif != nil {
		return *x.TokenWif
	}
	return ""
}

func (x *TransferFtRequest) GetToken() *TokenTransfer {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TransferFtRequest) GetFtChangeAddress() string {
	if x != nil && x.FtChangeAddress != nil {
		return *x.FtChangeAddress
	}
	return ""
}

func (x *TransferFtRequest) GetOpreturnData() []string {
	if x != nil {
		return x.OpreturnData
	}
	return nil
}

func (x *TransferFtRequest) GetChangeAddress() string {
	if x != nil && x.ChangeAddress != nil {
		return *x.ChangeAddress
	}
	return ""
}

type Receiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{1}
}

func (x *Receiver) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Receiver) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type TokenTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receivers  []*Receiver  `protobuf:"bytes,1,rep,name=receivers,proto3" json:"receivers,omitempty"`
	Codehash   string       `protobuf:"bytes,2,opt,name=codehash,proto3" json:"codehash,omitempty"`
	Genesis    string       `protobuf:"bytes,3,opt,name=genesis,proto3" json:"genesis,omitempty"`
	GasUtxos   []*GasUtxo   `protobuf:"bytes,4,rep,name=gasUtxos,proto3" json:"gasUtxos,omitempty"`
	TokenUtxos []*TokenUtxo `protobuf:"bytes,5,rep,name=tokenUtxos,proto3" json:"tokenUtxos,omitempty"`
}

func (x *TokenTransfer) Reset() {
	*x = TokenTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTransfer) ProtoMessage() {}

func (x *TokenTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTransfer.ProtoReflect.Descriptor instead.
func (*TokenTransfer) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{2}
}

func (x *TokenTransfer) GetReceivers() []*Receiver {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *TokenTransfer) GetCodehash() string {
	if x != nil {
		return x.Codehash
	}
	return ""
}

func (x *TokenTransfer) GetGenesis() string {
	if x != nil {
		return x.Genesis
	}
	return ""
}

func (x *TokenTransfer) GetGasUtxos() []*GasUtxo {
	if x != nil {
		return x.GasUtxos
	}
	return nil
}

func (x *TokenTransfer) GetTokenUtxos() []*TokenUtxo {
	if x != nil {
		return x.TokenUtxos
	}
	return nil
}

type GasUtxo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId        string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	OutputIndex *int32 `protobuf:"varint,2,opt,name=outputIndex,proto3,oneof" json:"outputIndex,omitempty"`
	Satoshis    string `protobuf:"bytes,3,opt,name=satoshis,proto3" json:"satoshis,omitempty"`
}

func (x *GasUtxo) Reset() {
	*x = GasUtxo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GasUtxo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasUtxo) ProtoMessage() {}

func (x *GasUtxo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasUtxo.ProtoReflect.Descriptor instead.
func (*GasUtxo) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{3}
}

func (x *GasUtxo) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *GasUtxo) GetOutputIndex() int32 {
	if x != nil && x.OutputIndex != nil {
		return *x.OutputIndex
	}
	return 0
}

func (x *GasUtxo) GetSatoshis() string {
	if x != nil {
		return x.Satoshis
	}
	return ""
}

type TokenUtxo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId        string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	OutputIndex *int32 `protobuf:"varint,2,opt,name=outputIndex,proto3,oneof" json:"outputIndex,omitempty"`
	TokenAmount string `protobuf:"bytes,3,opt,name=tokenAmount,proto3" json:"tokenAmount,omitempty"`
}

func (x *TokenUtxo) Reset() {
	*x = TokenUtxo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenUtxo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUtxo) ProtoMessage() {}

func (x *TokenUtxo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUtxo.ProtoReflect.Descriptor instead.
func (*TokenUtxo) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{4}
}

func (x *TokenUtxo) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TokenUtxo) GetOutputIndex() int32 {
	if x != nil && x.OutputIndex != nil {
		return *x.OutputIndex
	}
	return 0
}

func (x *TokenUtxo) GetTokenAmount() string {
	if x != nil {
		return x.TokenAmount
	}
	return ""
}

type TransferFtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  string          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *TransferFtData `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *TransferFtResponse) Reset() {
	*x = TransferFtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFtResponse) ProtoMessage() {}

func (x *TransferFtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFtResponse.ProtoReflect.Descriptor instead.
func (*TransferFtResponse) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{5}
}

func (x *TransferFtResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferFtResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferFtResponse) GetData() *TransferFtData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TransferFtData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId            string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	TxHex           string `protobuf:"bytes,2,opt,name=txHex,proto3" json:"txHex,omitempty"`
	RouteCheckTxHex string `protobuf:"bytes,3,opt,name=routeCheckTxHex,proto3" json:"routeCheckTxHex,omitempty"`
	RouteCheckTxId  string `protobuf:"bytes,4,opt,name=routeCheckTxId,proto3" json:"routeCheckTxId,omitempty"`
}

func (x *TransferFtData) Reset() {
	*x = TransferFtData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFtData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFtData) ProtoMessage() {}

func (x *TransferFtData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFtData.ProtoReflect.Descriptor instead.
func (*TransferFtData) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{6}
}

func (x *TransferFtData) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransferFtData) GetTxHex() string {
	if x != nil {
		return x.TxHex
	}
	return ""
}

func (x *TransferFtData) GetRouteCheckTxHex() string {
	if x != nil {
		return x.RouteCheckTxHex
	}
	return ""
}

func (x *TransferFtData) GetRouteCheckTxId() string {
	if x != nil {
		return x.RouteCheckTxId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  string      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *HealthData `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetData() *HealthData {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Network     string `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Timestamp   int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NoBroadcast bool   `protobuf:"varint,4,opt,name=noBroadcast,proto3" json:"noBroadcast,omitempty"`
}

func (x *HealthData) Reset() {
	*x = HealthData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metacontract_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthData) ProtoMessage() {}

func (x *HealthData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontract_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthData.ProtoReflect.Descriptor instead.
func (*HealthData) Descriptor() ([]byte, []int) {
	return file_proto_metacontract_proto_rawDescGZIP(), []int{9}
}

func (x *HealthData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthData) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *HealthData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthData) GetNoBroadcast() bool {
	if x != nil {
		return x.NoBroadcast
	}
	return false
}

var File_proto_metacontract_proto protoreflect.FileDescriptor

var file_proto_metacontract_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x74, 0x61,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0xaa, 0x02, 0x0a, 0x11, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x77, 0x69, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x77, 0x69, 0x66,
	0x12, 0x1f, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x57, 0x69, 0x66, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x57, 0x69, 0x66, 0x88, 0x01,
	0x01, 0x12, 0x31, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2d, 0x0a, 0x0f, 0x66, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0f, 0x66, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x70, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02,
	0x52, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x88,
	0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x57, 0x69, 0x66, 0x42,
	0x12, 0x0a, 0x10, 0x5f, 0x66, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0xe7, 0x01, 0x0a, 0x0d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x64, 0x65, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x64, 0x65, 0x68, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x73,
	0x69, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69,
	0x73, 0x12, 0x31, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x55, 0x74, 0x78, 0x6f, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x47, 0x61, 0x73, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x08, 0x67, 0x61, 0x73, 0x55,
	0x74, 0x78, 0x6f, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x74, 0x78,
	0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x74, 0x78,
	0x6f, 0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x74, 0x78, 0x6f, 0x73, 0x22, 0x70, 0x0a,
	0x07, 0x47, 0x61, 0x73, 0x55, 0x74, 0x78, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0b,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x73, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x78, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x74, 0x78, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64,
	0x12, 0x25, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x8c, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x78, 0x48,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x78, 0x48, 0x65, 0x78, 0x12,
	0x28, 0x0a, 0x0f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x48,
	0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x48, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x49,
	0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x7e, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x80, 0x01, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6e, 0x6f, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x32, 0xae, 0x01, 0x0a, 0x13, 0x4d, 0x65, 0x74, 0x61, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a,
	0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x74, 0x12, 0x1f, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x46, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x46, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x6d, 0x61, 0x6e, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_metacontract_proto_rawDescOnce sync.Once
	file_proto_metacontract_proto_rawDescData = file_proto_metacontract_proto_rawDesc
)

func file_proto_metacontract_proto_rawDescGZIP() []byte {
	file_proto_metacontract_proto_rawDescOnce.Do(func() {
		file_proto_metacontract_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_metacontract_proto_rawDescData)
	})
	return file_proto_metacontract_proto_rawDescData
}

var file_proto_metacontract_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_metacontract_proto_goTypes = []interface{}{
	(*TransferFtRequest)(nil),  // 0: metacontract.TransferFtRequest
	(*Receiver)(nil),           // 1: metacontract.Receiver
	(*TokenTransfer)(nil),      // 2: metacontract.TokenTransfer
	(*GasUtxo)(nil),            // 3: metacontract.GasUtxo
	(*TokenUtxo)(nil),          // 4: metacontract.TokenUtxo
	(*TransferFtResponse)(nil), // 5: metacontract.TransferFtResponse
	(*TransferFtData)(nil),     // 6: metacontract.TransferFtData
	(*HealthRequest)(nil),      // 7: metacontract.HealthRequest
	(*HealthResponse)(nil),     // 8: metacontract.HealthResponse
	(*HealthData)(nil),         // 9: metacontract.HealthData
}
var file_proto_metacontract_proto_depIdxs = []int32{
	2, // 0: metacontract.TransferFtRequest.token:type_name -> metacontract.TokenTransfer
	1, // 1: metacontract.TokenTransfer.receivers:type_name -> metacontract.Receiver
	3, // 2: metacontract.TokenTransfer.gasUtxos:type_name -> metacontract.GasUtxo
	4, // 3: metacontract.TokenTransfer.tokenUtxos:type_name -> metacontract.TokenUtxo
	6, // 4: metacontract.TransferFtResponse.data:type_name -> metacontract.TransferFtData
	9, // 5: metacontract.HealthResponse.data:type_name -> metacontract.HealthData
	0, // 6: metacontract.MetaContractService.TransferFt:input_type -> metacontract.TransferFtRequest
	7, // 7: metacontract.MetaContractService.GetHealth:input_type -> metacontract.HealthRequest
	5, // 8: metacontract.MetaContractService.TransferFt:output_type -> metacontract.TransferFtResponse
	8, // 9: metacontract.MetaContractService.GetHealth:output_type -> metacontract.HealthResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_metacontract_proto_init() }
func file_proto_metacontract_proto_init() {
	if File_proto_metacontract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_metacontract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GasUtxo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenUtxo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFtData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metacontract_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_metacontract_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_metacontract_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_proto_metacontract_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_proto_metacontract_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_proto_metacontract_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_metacontract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metacontract_proto_goTypes,
		DependencyIndexes: file_proto_metacontract_proto_depIdxs,
		MessageInfos:      file_proto_metacontract_proto_msgTypes,
	}.Build()
	File_proto_metacontract_proto = out.File
	file_proto_metacontract_proto_rawDesc = nil
	file_proto_metacontract_proto_goTypes = nil
	file_proto_metacontract_proto_depIdxs = nil
}
